In [ ]:
#ANN
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

dataset = load_digits()

x_train, x_test, y_train, y_test = train_test_split(dataset.data, dataset.target, test_size=0.20, random_state=4)

NN = MLPClassifier()

NN.fit(x_train, y_train)

y_pred = NN.predict(x_test)

accuracy = accuracy_score(y_test,y_pred)*100
print("Accuracy is: ",accuracy)

confusion_mat = confusion_matrix(y_test,y_pred)
print("Confusion matrix :\n ",confusion_mat)


Accuracy is:  98.05555555555556
Confusion matrix :
  [[37  0  0  0  0  0  0  1  0  0]
 [ 0 32  0  0  0  0  0  0  0  0]
 [ 0  0 41  0  0  0  0  0  0  0]
 [ 0  0  0 32  0  1  0  0  0  0]
 [ 0  1  0  0 36  0  0  0  0  0]
 [ 0  1  0  1  0 36  0  0  0  0]
 [ 0  0  0  0  0  0 35  0  0  0]
 [ 0  0  0  0  0  0  0 38  0  0]
 [ 0  2  0  0  0  0  0  0 31  0]
 [ 0  0  0  0  0  0  0  0  0 35]]
